#!/bin/bash

USERID=$(id -u)

#Colors
R="\e[31m"
G="\e[32m"
N="\e[0m"

#functions
CHECK_ROOT()
{
    if [ $USERID -ne 0]
    then
        echo "please run this script with root privieleges"
        exit 1
    fi
}

VALIDATE(){
    if [ $1 -ne 0 ]
    then 
        echo -e "$2 is... $R FAILED $N"
        exit 1
    else
        echo -e "$2 is... $G SUCCESS $N"
    fi
}

#USING FUNCTION
CHECK_ROOT

#SH 15-LOOPS-PKGS GIT MYSQL POSTFIX NGINX
for package in $@ #@ means refers to all arguments passed to it
do
    dnf list installed $package
    if [ $? -ne 0 ]
    then
        echo "$package is not installed, going to install it.."
        dnf install $package -y
        VALIDATE $? "Installing $package"
    else
        echo "$package is already installed..nothing to do"
    fi
done